image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo service mysql start
      mysql -u root -e "CREATE DATABASE testlink;"
      mysql -u root -e "CREATE USER 'testlink'@'localhost' IDENTIFIED BY 'testlink';"
      mysql -u root -e "GRANT ALL PRIVILEGES ON testlink.* TO 'testlink'@'localhost';"
      mysql -u root -e "FLUSH PRIVILEGES;"
      cd /workspace
      wget https://excellmedia.dl.sourceforge.net/project/testlink/TestLink%201.9.20/testlink-1.9.20.tar.gz
      tar -xvzf testlink-1.9.20.tar.gz
      sudo mv testlink-1.9.20 /var/www/html/testlink
      sudo chown -R www-data:www-data /var/www/html/testlink
      sudo chmod -R 755 /var/www/html/testlink
      cd /var/www/html/testlink
      sudo cp config_db.inc.php.example config_db.inc.php
      sudo sed -i "s/\$tlCfg->db->dbHost = 'localhost';/\$tlCfg->db->dbHost = 'localhost';/" config_db.inc.php
      sudo sed -i "s/\$tlCfg->db->dbName = 'testlink';/\$tlCfg->db->dbName = 'testlink';/" config_db.inc.php
      sudo sed -i "s/\$tlCfg->db->dbUser = 'testlink';/\$tlCfg->db->dbUser = 'testlink';/" config_db.inc.php
      sudo sed -i "s/\$tlCfg->db->dbPass = 'testlink';/\$tlCfg->db->dbPass = 'testlink';/" config_db.inc.php
      sudo service apache2 restart

ports:
  - port: 8080
    onOpen: open-preview
